<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MyTasks</name>
   <tag></tag>
   <elementGuidId>f88991a8-1a71-4f54-93bf-98d709b0dae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/ul/li[@id='tab-tasks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/ul/li[@id='tab-tasks']</value>
   </webElementProperties>
</WebElementEntity>
