<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MandatoryChecked-O1</name>
   <tag></tag>
   <elementGuidId>dc5da353-88d8-419b-86a2-e9b7b3e78f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;MandatoryChecked&quot;]/label[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;MandatoryChecked&quot;]/label[1]/span</value>
   </webElementProperties>
</WebElementEntity>
