<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Both_Label_Japanese</name>
   <tag></tag>
   <elementGuidId>593d859f-cca8-44dd-949c-3d1909818562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctrlField104&quot;]/div/label[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctrlField104&quot;]/div/label[1]/span</value>
   </webElementProperties>
</WebElementEntity>
