<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Both_Label_Chinese</name>
   <tag></tag>
   <elementGuidId>dd9cbd69-0be2-442e-a94f-dd2e9320277f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctrlField103&quot;]/div/label[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctrlField103&quot;]/div/label[1]/span</value>
   </webElementProperties>
</WebElementEntity>
